version: "3.9"

services:
  data-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-pipeline-container
    ports:
      - "8000:8000"
    volumes:
      - ./Pipeline:/app/Pipeline
      - ./sample_logs:/app/sample_logs
    working_dir: /app
    command: uvicorn Pipeline.api:app --host 0.0.0.0 --port 8000 --reload

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
